### ISSUE TITLE
也許試著將 C++ 版本改為 PHP Extension 會有效率些？

### ISSUE THREAD

**Issue by kiang** [fukuball/jieba-php#1]
畢竟 PHP 處理大量字串的效能不是挺好，當然，如果你只是想實驗看看能否移轉同樣演算法的話就另當別論了 XD

**Comment by fukuball** [comment]
哈哈哈 我希望用單純的 PHP 來做看看，這樣才可以促進 PHP 這個程式語言發展嘛！
