### ISSUE TITLE
关于词频的问题

### ISSUE THREAD

**Issue by hainuo** [fukuball/jieba-php#13]
我现在使用jieba 分词来处理系统的关键词，但是有好多并不是我想要的。我觉得如果我可以生成一个自己的词频词库或许能够更好地提取关键词。所以想问一下，我应该如何训练 jieba 生成自己的词库呢

**Comment by fukuball** [comment]
@hainuo 你想訓練哪個部分呢？字典、hmm 模型或是 idf 詞頻？

**Comment by hainuo** [comment]
现在基础的专业词汇没有先训练字典吧

发自我的 iPhone

**Comment by fukuball** [comment]
@hainuo 不懂你的需求，結巴目前的運作原理就是先用字典斷詞再用 HMM 找新詞，某種程度字典決定了結巴的準確度，字典的詞頻如何產生，對結巴來說就是訓練過程
