### ISSUE TITLE
升級 jieba-php 0.20 版本

### ISSUE THREAD

**Issue by fukuball** [fukuball/jieba-php#2]
找個時間來升級成  jieba-php 0.20 版本，有人想幫忙可以事先跟我說，不然我就自己來做囉～

**Comment by theringe** [comment]
您好，我是路過的使用者，超感謝您願意改寫這麼好用的資源，以下指出一些實際套用發生的問題方便您日後的改版：

1. 我使用 php 5.3 ，所以 JsonSerializable 無法使用，必須另外下載
https://github.com/packfire/php5.3-compatibility/blob/master/src/JsonSerializable.php

2. src\vendor\multi-array\MultiArray.php 這個檔案的陣列宣告方式也因為要向下相容於 php 5.3 所以我將 所有的 [] 都置換為 array()

**Comment by fukuball** [comment]
@theringe 好的，會考慮進去做改版～

**Comment by fukuball** [comment]
@theringe 最新版已改成向下支援 php 5.3

**Comment by theringe** [comment]
這個套件真是好用，我把用了多年笨重的 CKIPCLI+WINE 直接丟掉

**Comment by fukuball** [comment]
@theringe 對啊，我快有時間把它升級到 0.20 版了，可能再過幾天吧～

**Comment by fukuball** [comment]
jieba-php 0.20 版已經釋出～ https://github.com/fukuball/jieba-php/releases/tag/0.20
