### ISSUE TITLE
结巴分词php版本支持停用词吗？

### ISSUE THREAD

**Issue by qxiaomay** [fukuball/jieba-php#21]
就比如“的”，“我”，“你们”，“他们”等等

**Comment by fukuball** [comment]
@qxiaomay 哎呀 我還沒翻譯到那邊，目前還沒有～

**Comment by kinkievan** [comment]
請問一下何時才會出呢????

**Comment by fukuball** [comment]
@kinkievan  還沒開始做耶，近期會找時間弄一下～

**Comment by fukuball** [comment]
0.33 版已經支援 Stop Words，關掉這個 issue 了
