### ISSUE TITLE
请问如何提高执行速度

### ISSUE THREAD

**Issue by graycatclub** [fukuball/jieba-php#23]
您好：
我用的small库，每次一句有10个汉子左右，可是每次执行都要3-4秒，如何能提高速度呢，精简词库也可以。

**Comment by fukuball** [comment]
您好，目前主要的瓶頸在載入詞典的時候，只要詞典載入之後，多少句子、多少字數基本上不會影響到太多時間，因此在做分詞前處理時可以考慮一次將所有文本進行分詞，而不要一句一句來執行，以避過前面必要載入詞典的 over head（3 secs）。

**Comment by graycatclub** [comment]
您好，請問載入詞典是哪一個檔案呢？我想去精簡詞典，這樣可以提高速度嗎？我寫的是一個網頁程式，用戶按鍵就返回結果。要分詞的句子只有十個字符左右，而最終結果，可能1-2個詞就夠了。
謝謝您！

**Comment by graycatclub** [comment]
不好意思，是我拼错。改用small库，1秒出结果，应该可以接受了，谢谢您！

**Comment by fukuball** [comment]
@graycatclub 喔喔 好的 沒問題～
