### ISSUE TITLE
希望考虑添加过滤开关来选择是否过滤日语和韩语

### ISSUE THREAD

**Issue by dfc643** [fukuball/jieba-php#24]
你好开发者，结巴分词目前用过比较完善且简单好用的分词系统。

但是在某些特定的情况下可能想要分词的时候保留日语、韩语原文。
希望能够添加参数开关来选择是否过滤日语和韩语。

**Comment by fukuball** [comment]
的確是可以考慮增加這個參數，不過我目前個人時間不太夠用，也許不會這麼快做到這個功能，如果有人能幫忙那就太好了 XD
