### ISSUE TITLE
Jieba.php line 280 Call to a member function exists() on array

### ISSUE THREAD

**Issue by kangkang66** [fukuball/jieba-php#26]
FatalErrorException in Jieba.php line 280:
Call to a member function exists() on array

version:0.25

**Comment by fukuball** [comment]
do you require these libraries?

```
require_once "/path/to/your/vendor/multi-array/MultiArray.php";
require_once "/path/to/your/vendor/multi-array/Factory/MultiArrayFactory.php";
```

**Comment by zplzpl** [comment]
出现同样的问题，使用YII2框架，使用composer安装。

autoload_files.php 部分内容

`    'f40cb564d92ad0e78b0bfdf9b86c5768' => $vendorDir . '/fukuball/jieba-php/src/class/Jieba.php',
    'a778fafb0619406705f6fd4bb3ec7d5b' => $vendorDir . '/fukuball/jieba-php/src/class/JiebaAnalyse.php',
    '06c61fd667b7f3d9ee59d805e51017e7' => $vendorDir . '/fukuball/jieba-php/src/class/Finalseg.php',
    '750aa4fdf8bfc24d7baef293581bec73' => $vendorDir . '/fukuball/jieba-php/src/class/Posseg.php',
    '6ca3f08a814c4fd9d5830fc6808a9488' => $vendorDir . '/fukuball/jieba-php/src/vendor/multi-array/MultiArray.php',
    '4d5ee3c1cc66ee941937c247fe6b7d6e' => $vendorDir . '/fukuball/jieba-php/src/vendor/multi-array/Factory/MultiArrayFactory.php',
`

使用的版本：dev-master

**Comment by fukuball** [comment]
<img width="1272" alt="2017-09-06 6 12 22" src="https://user-images.githubusercontent.com/646843/30106767-21e323ae-932f-11e7-950d-2b52335257cb.png">
<img width="1278" alt="2017-09-06 6 14 07" src="https://user-images.githubusercontent.com/646843/30106781-2c913d86-932f-11e7-9dcc-aa97742720f0.png">
<img width="1271" alt="2017-09-06 6 12 42" src="https://user-images.githubusercontent.com/646843/30106797-37849bca-932f-11e7-8d91-028c9e46ee8b.png">

我實在是無法 reproduce 這個問題，所以目前不知如何修

**Comment by jokercoplay** [comment]
Have you done the init operation?
