### ISSUE TITLE
JiebaAnalyse::extractTags 执行50次要4秒多，请问有什么好的解决方式吗

### ISSUE THREAD

**Issue by carolspirit** [fukuball/jieba-php#27]
JiebaAnalyse::extractTags 执行50次要4秒多，请问有什么好的解决方式吗

**Comment by fukuball** [comment]
目前速度似乎就是這樣，不容易再改得更快了，可能需要其他強者大大幫忙一下

**Comment by eddy8** [comment]
请问版本不更新了吗，jieba到0.39版了 @fukuball

**Comment by fukuball** [comment]
@eddy8 會再更新的，目前分身乏術，速度慢了

**Comment by eddy8** [comment]
@fukuball 辛苦~

**Comment by carolspirit** [comment]
@tianhe1986 感谢，测试了一下，确实速度有提升。感谢，也感谢@fukuball。
