### ISSUE TITLE
浏览器 错误代码： ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by pangshou** [fukuball/jieba-php#30]
无法看到输出结果，想问是不是缓存或是环境的问题呢？

**Comment by pangshou** [comment]
匿去ini_set('memory_limit', '1024M'); 后，看到
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 76 bytes) in src/vendor/multi-array/MultiArray.php on line 64

**Comment by fukuball** [comment]
感覺是環境問題耶
