### ISSUE TITLE
linux 服务器 php7.2

### ISSUE THREAD

**Issue by wuwu123** [fukuball/jieba-php#37]
Undefined index: B" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(8) ["file":protected]=> string(69) "/home/www/wechat_api/vendor/fukuball/jieba-php/src/class/Finalseg.php"

**Comment by fukuball** [comment]
目前 Travis-CI 更新到支援 PHP 7.2，測試通過沒發現問題

**Comment by fukuball** [comment]
Close 囉
