### ISSUE TITLE
Laravel 使用总是报错

### ISSUE THREAD

**Issue by dongkaipo** [fukuball/jieba-php#38]
一般会出现三种情况：

1. 报错500没有任何返回信息，页面崩溃
2. 报错内存`"Allowed memory size of 134217728 bytes exhausted (tried to allocate 18874368 bytes)"`但是 php 内存已经设定到了 1G 了。
3. 正常输出结果

这三种情况会随机出现。Laravel 版本是 5.6

**Comment by fukuball** [comment]
這看起來 php 的 memory_limit 還是沒有設定好，僅有 134217728 bytes，也就是只有 128 mb，調高 memory_limit 應該會有幫助
