### ISSUE TITLE
你好，laravel5.5 初始化init的时候错误

### ISSUE THREAD

**Issue by bestcyt** [fukuball/jieba-php#42]
你好，我在控制器中初始化这两个Jieba::init();Finalseg::init();

线上环境500 ； 本地没有问题；

注释掉这两句后，网页正常打开；

在这两句前后dd('test')；正常；

就是init的时候不知道什么问题，laravel.log没有记录；network显示500没有提示信息

**Comment by bestcyt** [comment]
加了1024m内存 好了 ； 但是是不是就炸了，是不是我服务器内存太少了》？

**Comment by xiaosanye** [comment]
@bestcyt  你好，请问读写炸了，之后怎么解决呢

**Comment by xiaosanye** [comment]
每次执行之后，缓存增大，进程解锁，没有释放，这个是怎么处理的

**Comment by fukuball** [comment]
如果本地端可以，但產品端出問題，那的確是環境問題，通常就是 memory 不夠用

**Comment by bestcyt** [comment]
@xiaosanye  嗯，我是换了个分词方案，换了scws，我这有写一个简单使用的文章你可以参考一下https://laravel-china.org/articles/13601/the-use-of-php-thesaurus-jieba-and-scws-in-laravel

**Comment by fukuball** [comment]
https://github.com/fukuball/jieba-php/issues/49

**Comment by fukuball** [comment]
已在 master 改善這問題囉
