### ISSUE TITLE
创建自定义字典的那个n，nr是什么意思？还有能否创建标点符号的字典

### ISSUE THREAD

**Issue by bestcyt** [fukuball/jieba-php#44]
创建自定义字典的那个n，nr是什么意思？还有能否创建标点符号的字典；比如这一句话：云计算李小“福创”办，的啊 ， 我想在cut后出现两个 “ 这样的数组元素？该怎么添加字典呢？求解

**Comment by fukuball** [comment]
請見詞性說明：https://gist.github.com/luw2007/6016931，目前有些標點符號會直接濾掉
