### ISSUE TITLE
关于若干请求后，内存溢出问题

### ISSUE THREAD

**Issue by xiaosanye** [fukuball/jieba-php#46]
因为PHP无法常驻内存，所有每个对象都是page Scope的，用户每次的请求都会重新初始化一遍jieba-php的服务，现在遇到缓存无法释放，执行若干次后，内存溢出，请问你们是怎么处理的

**Comment by xiaosanye** [comment]
@fukuball

**Comment by fukuball** [comment]
通常斷詞這樣的處理都會是離線處理的，目前 jieba-php 佔用的內存較大，也因此不太會直接在網頁上初始化 jieba-php，如果非得在網頁上使用，可以在每次使用後將物件刪除（將物件設為 null 再 unset）以釋放 memory，不過如果多人同時使用還是會爆，還是想辦法離線處理較好。

jieba-php 佔用較大的內存需要花時間解決，我再花一些時間來研究看看好了

**Comment by fukuball** [comment]
https://github.com/fukuball/jieba-php/issues/49

**Comment by xiaosanye** [comment]
谢谢了,我也研究一下

**Comment by fukuball** [comment]
已在 master 改善這問題囉
