### ISSUE TITLE
能否支持下 PHP 8.1

### ISSUE THREAD

**Issue by likunyan** [fukuball/jieba-php#76]
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/7204604/164689347-5e75d482-6bb5-4891-83a7-37165ab4588d.png">

**Comment by kingispeak** [comment]
有發 PR，不過一直沒 Merge

**Comment by likunyan** [comment]
另起炉灶吧

**Comment by fukuball** [comment]
@kingispeak @likunyan 已發佈更新，如果有任何問題，請再幫忙貢獻，感謝！
